BTCPayServer/Controllers/UIHomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Contracts;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Client;
using BTCPayServer.Components.StoreSelector;
using BTCPayServer.Data;
using BTCPayServer.Filters;
using BTCPayServer.HostedServices;
using BTCPayServer.Models;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Payments;
using BTCPayServer.Payments.Lightning;
using BTCPayServer.Security;
using BTCPayServer.Services;
using BTCPayServer.Services.Apps;
using BTCPayServer.Services.Stores;
using ExchangeSharp;
using Google.Apis.Auth.OAuth2;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using NBitcoin;
using NBitcoin.Payment;
using NBitpayClient;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BTCPayServer.Controllers
{
    public class UIHomeController : Controller
    {
        private readonly ThemeSettings _theme;
        private readonly StoreRepository _storeRepository;
        private readonly BTCPayNetworkProvider _networkProvider;
        private IHttpClientFactory HttpClientFactory { get; }
        private SignInManager<ApplicationUser> SignInManager { get; }
        public LanguageService LanguageService { get; }

        public UIHomeController(IHttpClientFactory httpClientFactory,
                              ThemeSettings theme,
                              LanguageService languageService,
                              StoreRepository storeRepository,
                              BTCPayNetworkProvider networkProvider,
                              SignInManager<ApplicationUser> signInManager)
        {
            _theme = theme;
            HttpClientFactory = httpClientFactory;
            LanguageService = languageService;
            _networkProvider = networkProvider;
            _storeRepository = storeRepository;
            SignInManager = signInManager;
        }

        [HttpGet("home")]
        public Task<IActionResult> Home()
        {
            return Index();
        }

        [Route("")]
        [DomainMappingConstraint]
        public async Task<IActionResult> Index()
        {
            if (_theme.FirstRun)
            {
                return RedirectToAction(nameof(UIAccountController.Register), "UIAccount");
            }

            if (SignInManager.IsSignedIn(User))
            {
                var userId = SignInManager.UserManager.GetUserId(HttpContext.User);
                var storeId = HttpContext.GetUserPrefsCookie()?.CurrentStoreId;
                if (storeId != null)
                {
                    // verify store exists and redirect to it
                    var store = await _storeRepository.FindStore(storeId, userId);
                    if (store != null)
                    {
                        return RedirectToStore(store);
                    }
                }
                
                var stores = await _storeRepository.GetStoresByUserId(userId);
                if (stores.Any())
                {
                    // redirect to first store
                    return RedirectToStore(stores.First());
                }
                
                var vm = new HomeViewModel
                {
                    HasStore = stores.Any()
                };
                
                return View("Home", vm);
            }

            return Challenge();
        }

        [Route("misc/lang")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Languages()
        {
            return Json(LanguageService.GetLanguages(), new JsonSerializerSettings { Formatting = Formatting.Indented });
        }

        [Route("misc/permissions")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Permissions()
        {
            return Json(Client.Models.PermissionMetadata.PermissionNodes, new JsonSerializerSettings { Formatting = Formatting.Indented });
        }

        [Route("swagger/v1/swagger.json")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public async Task<IActionResult> Swagger([FromServices] IEnumerable<ISwaggerProvider> swaggerProviders)
        {
            JObject json = new();
            var res = await Task.WhenAll(swaggerProviders.Select(provider => provider.Fetch()));
            foreach (JObject jObject in res)
            {
                json.Merge(jObject);
            }
            var servers = new JArray();
            servers.Add(new JObject(new JProperty("url", HttpContext.Request.GetAbsoluteRoot())));
            json["servers"] = servers;
            var tags = (JArray)json["tags"];
            json["tags"] = new JArray(tags
                .Select(o => (name: ((JObject)o)["name"].Value<string>(), o))
                .OrderBy(o => o.name)
                .Select(o => o.o)
                .ToArray());
            return Json(json);
        }

        [Route("docs")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
        public IActionResult SwaggerDocs()
        {
            return View();
        }

        [Route("recovery-seed-backup")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
        public IActionResult RecoverySeedBackup(RecoverySeedBackupViewModel vm)
        {
            return View("RecoverySeedBackup", vm);
        }

        [HttpPost]
        [Route("postredirect-callback-test")]
        public ActionResult PostRedirectCallbackTestpage(IFormCollection data)
        {
            var list = data.Keys.Aggregate(new Dictionary<string, string>(), (res, key) =>
            {
                res.Add(key, data[key]);
                return res;
            });
            return Json(list);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public RedirectToActionResult RedirectToStore(StoreData store)
        {
            return store.Role == StoreRoles.Owner 
                ? RedirectToAction("Dashboard", "UIStores", new { storeId = store.Id }) 
                : RedirectToAction("ListInvoices", "UIInvoice", new { storeId = store.Id });
        }
    }
}

BTCPayServer/Views/Shared/Confirm.cshtml
@model BTCPayServer.Abstractions.Models.ConfirmModel

@{
    ViewData["Title"] = Model.Title;
    Layout = "_LayoutSimple";
}

@section PageHeadContent {
    <style>
        body > .content-wrapper { display: flex; min-height: 100vh; }
        .modal-dialog .btn-close { display: none; }
    </style>
}

@section PageFootContent {
    <script>
        document.getElementById('ConfirmCancel').addEventListener('click', function () {
            history.back();
            return false;
        })
    </script>
}

<partial name="ConfirmModal" model="Model" />

BTCPayServer/Views/Shared/EmailsBody.cshtml
@model BTCPayServer.Models.ServerViewModels.EmailsViewModel

<div class="row">
    <div class="col-xl-10 col-xxl-constrain">
        <div class="d-flex flex-wrap gap-3 align-items-center justify-content-between mt-n1 mb-4">
            <h3 class="mb-0">Email Server</h3>
            <div class="d-flex">
                <div class="dropdown only-for-js" id="quick-fill">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="QuickFillDropdownToggle">
                        Quick Fill
                    </button>
                    <div class="dropdown-menu" aria-labelledby="QuickFillDropdownToggle">
                        <a class="dropdown-item" href="" data-server="smtp.gmail.com" data-port="587">Gmail.com</a>
                        <a class="dropdown-item" href="" data-server="mail.yahoo.com" data-port="587">Yahoo.com</a>
                        <a class="dropdown-item" href="" data-server="smtp.mailgun.org" data-port="587">Mailgun</a>
                        <a class="dropdown-item" href="" data-server="smtp.office365.com" data-port="587">Office365</a>
                        <a class="dropdown-item" href="" data-server="smtp.sendgrid.net" data-port="587">SendGrid</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" autocomplete="off">
    <div class="row">
        <div class="col-xl-10 col-xxl-constrain">
            @if (!ViewContext.ModelState.IsValid)
            {
                <div asp-validation-summary="All" class="text-danger"></div>
            }
            <div class="form-group">
                <label asp-for="Settings.Server" class="form-label">SMTP Server</label>
                <input asp-for="Settings.Server" data-fill="server" class="form-control"/>
                <span asp-validation-for="Settings.Server" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Port" class="form-label"></label>
                <input asp-for="Settings.Port" data-fill="port" class="form-control"/>
                <span asp-validation-for="Settings.Port" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.From" class="form-label">Sender's Email Address</label>
                <input asp-for="Settings.From" class="form-control" placeholder="Firstname Lastname <email@example.com>" />
                <span asp-validation-for="Settings.From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Login" class="form-label"></label>
                <input asp-for="Settings.Login" class="form-control"/>
                <small class="form-text text-muted">
                    For many email providers (like Gmail) your login is your email address.
                </small>
                <span asp-validation-for="Settings.Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                @if (!Model.PasswordSet)
                {

                    <label asp-for="Settings.Password" class="form-label"></label>
                    <input asp-for="Settings.Password" type="password" class="form-control"/>
                    <span asp-validation-for="Settings.Password" class="text-danger"></span>
                }
                else
                {
                    <label asp-for="Settings.Password" class="form-label"></label>
                    <div class="input-group">
                        <input value="Configured" type="text" readonly class="form-control"/>
                        <button type="submit" class="btn btn-danger" name="command" value="ResetPassword" id="ResetPassword">Reset</button>
                    </div>
                }
            </div>
            <input asp-for="PasswordSet" type="hidden"/>
			<div class="my-4">
                <button class="d-inline-flex align-items-center btn btn-link text-primary fw-semibold p-0" type="button" id="AdvancedSettingsButton" data-bs-toggle="collapse" data-bs-target="#AdvancedSettings" aria-expanded="false" aria-controls="AdvancedSettings">
                    <vc:icon symbol="caret-down"/>
                    <span class="ms-1">Advanced settings</span>
                </button>
                <div id="AdvancedSettings" class="collapse">
                    <div class="pt-3 pb-1">
                        <div class="form-group">
                            <div class="form-check">
                                <input asp-for="Settings.DisableCertificateCheck" class="form-check-input" />
                                <label asp-for="Settings.DisableCertificateCheck" class="form-check-label">Disable TLS certificate security checks</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-2" name="command" value="Save" id="Save">Save</button>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-8 col-xxl-constrain">
            <div class="form-group">
                <h3 class="mt-5 mb-3">Testing</h3>
                <p>
                    To test your settings, enter an email address below.
                </p>
                <label asp-for="TestEmail" class="form-label"></label>
                <input asp-for="TestEmail" placeholder="Firstname Lastname <email@example.com>" class="form-control" />
                <span asp-validation-for="TestEmail" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-secondary mt-2" name="command" value="Test" id="Test">Send Test Email</button>
        </div>
    </div>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        delegate('click', '#quick-fill .dropdown-menu a', function (e) {
            e.preventDefault();
            
            const data = e.target.dataset;
            Object.keys(data).forEach(function (key) {
                const value = data[key];
                const input = document.querySelector('input[data-fill="' + key + '"]');
                if (input) {
                    const type = input.getAttribute('type');
                    if (type === 'checkbox') {
                        input.checked = value;
                    } else {
                        input.value = value;
                    }
                }
            });
        });
    });
</script>

BTCPayServer/Views/Shared/NotificationEmailWarning.cshtml
<div class="alert alert-warning alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <vc:icon symbol="close" />
    </button>
    The Email settings have not been configured on this server or store yet. Setting this field will not send emails until then. <a asp-action="StoreEmailSettings" asp-controller="UIStores" asp-route-storeId="@Model" class="alert-link">Configure store email settings</a>
</div>

BTCPayServer/Views/Shared/ShowQR.cshtml
<div id="scan-qr-modal-app">
    <div class="modal" tabindex="-1" role="dialog" :id="modalId">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{title}} <template v-if="fragments && fragments.length > 1">({{index+1}}/{{fragments.length}})</template></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <vc:icon symbol="close"/>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <div class="text-center mt-3" :style="{height: `${qrOptions.height}px`}">
                        <component v-if="currentFragment" :is="currentMode.href ? 'a': 'div'" class="qr-container d-inline-block" :href="currentMode.href">
                            <qrcode :value="currentFragment" :options="qrOptions"></qrcode>
                        </component>
                    </div>
                    <ul class="nav justify-content-center mt-4 mb-3" v-if="modes && Object.keys(modes).length > 1">
                        <li class="nav-item" v-for="(item, key) in modes">
                            <a class="btcpay-pill" :class="{ 'active': key === mode }" href="#" v-on:click="mode = key">{{item.title}}</a>
                        </li>
                    </ul>
                    <div v-if="currentFragment && currentMode.showData">
                        <div class="input-group input-group-sm" :data-clipboard="currentFragment">
                            <input type="text" class="form-control" style="cursor:copy" readonly="readonly" :value="currentFragment" id="qr-code-data-input">
                            <button type="button" class="btn btn-outline-secondary" data-clipboard-confirm="">Copy</button>
                        </div>
                    </div>
                    <p v-if="note" v-html="note" class="text-muted mt-3"></p>
                </div>
                <div class="mb-4 text-center" v-if="continueCallback">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" v-on:click="continueCallback()">{{ continueTitle || 'Continue' }}</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
function initQRShow(data) {
 	return new Vue({
 		el: '#scan-qr-modal-app',
 		components: {
 			qrcode: VueQrcode
 		},
 		data() {
             const res = Object.assign({}, {
                 title: "Scan QR",
                 modalId: "scan-qr-modal",
                 modes: {},
                 index: -1,
                 speed: 500,
                 active: false,
                 note: null,
                 continueTitle: null,
                 continueCallback: null,
                 qrOptions: {
                     width: 256,
                     height: 256,
                     margin: 1,
                     color: {
                         dark: '#000',
                         light: '#f5f5f7'
                     }
                 }
             }, data || {});
             
             if (!Object.values(res.modes || {}).length) {
                 res.modes = { default: { title: 'Default', fragments: [res.data] } };
             }
             
             if (!res.mode) {
                res.mode = Object.keys(res.modes)[0];
             }
   
             return res;
 		},
 		computed: {
             fragments() {
                 return this.currentMode && this.currentMode.fragments;
             },
             currentMode() {
                 return this.modes[this.mode];
             },
             currentFragment() {
                 return this.fragments && this.fragments[this.index];
             }
 		},
 		mounted() {
 			$(`#${this.modalId}`)
 				.on("shown.bs.modal", () => { this.start(); })
 				.on("hide.bs.modal", () => { this.active = false; });
 		},
 		methods: {
 			start() {
                 this.active = true;
                 this.index = -1;
                 this.playNext();
 			},
 			playNext() {
                 if (!this.active) return;
                 
                 this.index++;
                 if (this.index > (this.fragments.length - 1)) {
                     this.index = 0;
                 }
                 setTimeout(this.playNext, this.speed);
 			},
 			showData(data) {
                this.modes = { default: { title: 'Default', fragments: [data] } };
                
                $(`#${this.modalId}`).modal("show");
            }
 		}
 	});
 }
 </script>

BTCPayServer/Views/Shared/VaultElements.cshtml
<script id="VaultConnection" type="text/template">
    <div class="vault-feedback vault-feedback1 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-grow"></span>
    </div>
    <div class="vault-feedback vault-feedback2 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-grow"></span>
    </div>
    <div class="vault-feedback vault-feedback3 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-grow"></span>
    </div>
    <div id="pin-input" class="mt-4" style="display: none;">
        <div class="row">
            <div class="col">
                <div class="input-group mb-2">
                    <input id="pin-display" type="text" class="form-control" readonly>
                    <div id="pin-display-delete" class="input-group-text cursor-pointer"><span class="fa fa-remove"></span></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-7"></div></div>
            <div class="col"><div class="pin-button" id="pin-8"></div></div>
            <div class="col"><div class="pin-button" id="pin-9"></div></div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-4"></div></div>
            <div class="col"><div class="pin-button" id="pin-5"></div></div>
            <div class="col"><div class="pin-button" id="pin-6"></div></div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-1"></div></div>
            <div class="col"><div class="pin-button" id="pin-2"></div></div>
            <div class="col"><div class="pin-button" id="pin-3"></div></div>
        </div>
    </div>
    <div id="passphrase-input" class="mt-4" style="display: none;">
        <div class="form-group">
            <label for="Password" class="input-group-text"><span class="input-group-addon fa fa-lock"></span></label>
            <input id="Password" type="password" class="form-control" placeholder="Passphrase" />
        </div>
        <div class="form-group">
            <div class="input-group">
                <label for="PasswordConfirmation" class="input-group-text"><span class="input-group-addon fa fa-lock"></span></label>
                <input id="PasswordConfirmation" type="password" class="form-control" placeholder="Passphrase confirmation" />
            </div>
        </div>
    </div>
</script>

BTCPayServer/Views/Shared/_Confirm.cshtml
@model BTCPayServer.Abstractions.Models.ConfirmModel
<div class="modal fade" id="ConfirmModal" tabindex="-1" aria-labelledby="ConfirmTitle" aria-hidden="true">
    <partial name="ConfirmModal" model="Model" />
</div>

<script>
    const modal = document.getElementById('ConfirmModal')
    modal.addEventListener('show.bs.modal', event => {
        const $target = event.relatedTarget
        const $form = document.getElementById('ConfirmForm')
        const $text = document.getElementById('ConfirmText')
        const $title = document.getElementById('ConfirmTitle')
        const $description = document.getElementById('ConfirmDescription')
        const $input = document.getElementById('ConfirmInput')
        const $inputText = document.getElementById('ConfirmInputText')
        const $continue = document.getElementById('ConfirmContinue')
        const { title, description, confirm, confirmInput } = $target.dataset
        const action = $target.dataset.action || ($target.nodeName === 'A'
            ? $target.getAttribute('href')
            : $target.form.getAttribute('action'))

        if ($form && !$form.hasAttribute('action')) $form.setAttribute('action', action)
        if (title) $title.textContent = title
        if (description) $description.innerHTML = description
        if (confirm) $continue.textContent = confirm
        if (confirmInput) {
            $text.removeAttribute('hidden')
            $continue.setAttribute('disabled', 'disabled')
            $inputText.textContent = confirmInput
            $input.setAttribute("autocomplete", "off")
            $input.addEventListener('input', event => {
                event.target.value.trim() === confirmInput
                    ? $continue.removeAttribute('disabled')
                    : $continue.setAttribute('disabled', 'disabled')
            })
            $form.addEventListener('submit', event => {
                if ($input.value.trim() !== confirmInput) {
                    event.preventDefault()
                }
            })
        } else {
            $text.setAttribute('hidden', 'hidden')
            $continue.removeAttribute('disabled')
        }
    });
    modal.addEventListener('shown.bs.modal', event => {
        const $target = event.relatedTarget
        const $input = document.getElementById('ConfirmInput')
        const { confirmInput } = $target.dataset
        if (confirmInput) {
            $input.focus();
        }
    });
</script>

BTCPayServer/Views/Shared/_Footer.cshtml
@using BTCPayServer.Abstractions.Extensions
@inject BTCPayServer.Services.BTCPayServerEnvironment _env

<footer class="btcpay-footer">
    <div class="d-flex flex-wrap flex-column justify-content-between flex-xl-row gap-3">
        <div class="d-flex flex-wrap justify-content-center justify-content-xl-start gap-4">
            <a href="https://github.com/btcpayserver/btcpayserver" class="d-flex align-items-center" target="_blank" rel="noreferrer noopener">
                <vc:icon symbol="github"/>
                <span style="margin-left:.4rem">Github</span>
            </a>
            <a href="https://chat.btcpayserver.org/" class="d-flex align-items-center" target="_blank" rel="noreferrer noopener">
                <vc:icon symbol="mattermost"/>
                <span style="margin-left:.4rem">Mattermost</span>
            </a>
            <a href="https://twitter.com/BtcpayServer" class="d-flex align-items-center" target="_blank" rel="noreferrer noopener">
                <vc:icon symbol="twitter"/>
                <span style="margin-left:.4rem">Twitter</span>
            </a>
            <a href="https://t.me/btcpayserver" class="d-flex align-items-center" target="_blank" rel="noreferrer noopener">
                <vc:icon symbol="telegram"/>
                <span style="margin-left:.4rem">Telegram</span>
            </a>
            <a href="https://btcpayserver.org/donate/" class="d-flex align-items-center" target="_blank" rel="noreferrer noopener">
                <vc:icon symbol="donate"/>
                <span style="margin-left:.4rem">Donate</span>
            </a>
            @if (!string.IsNullOrEmpty(_env.OnionUrl) && !Context.Request.IsOnion())
            {
                <a href="@_env.OnionUrl" class="d-flex align-items-center" target="_onion" rel="noreferrer noopener" role="button" data-clipboard="@_env.OnionUrl" style="min-width:9em;">
                    <vc:icon symbol="onion"/>
                    <span style="margin-left:.4rem" data-clipboard-confirm="Copied URL ✔">Copy Tor URL</span>
                </a>
            }
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="text-center">
                @_env.ToString()
            </div>
        }
    </div>
</footer>

BTCPayServer/Views/Shared/_FormTopMessages.cshtml
@model BTCPayServer.Abstractions.Form.Form
@using ExchangeSharp

@if (Model.TopMessages.Count > 0)
{
    @foreach (var alertMessage in Model.TopMessages)
    {
        <p class="alert alert-@alertMessage.Type.ToStringLowerInvariant()">@alertMessage.Message</p>
    }
}

BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
@{
    Layout = "_LayoutSimple";
    ViewBag.ShowTitle ??= true;
    ViewBag.ShowLeadText ??= false;
}

@section PageHeadContent {
    <style>
        .account-form {
            max-width: 35em;
            margin: 0 auto var(--btcpay-space-xl);
            padding: 2rem;
            background: var(--btcpay-bg-tile);
            border-radius: var(--btcpay-border-radius);
        }
        .account-form h4 {
            margin-bottom: 1.5rem;
        }
        .main-logo { height: 4rem; width: 18rem; }
        .main-logo.main-logo-btcpay { height: 4.5rem; width: 2.5rem; }
        .main-logo-btcpay .main-logo-btcpay--large { display: none; }
    </style>
    @await RenderSectionAsync("PageHeadContent", false)
}

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("PageFootContent", false)
}

<div class="row justify-content-center mb-2">
    <div class="col text-center">
        <a asp-controller="UIHome" asp-action="Index" tabindex="-1" class="d-inline-block navbar-brand mx-0 mb-4">
            <vc:main-logo />
        </a>

        <h1 class="h2 mb-3">Welcome to your BTCPay&nbsp;Server</h1>
        @if (ViewBag.ShowLeadText)
        {
            <p class="lead">
                <span class="d-sm-block">A self-hosted, open-source bitcoin payment processor.</span>
                <span class="d-sm-block">It is secure, private, censorship-resistant and free.</span>
            </p>
        }

        <partial name="_StatusMessage"/>
    </div>
</div>

<div class="account-form">
    @if (ViewBag.ShowTitle)
    {
        <h4>@ViewData["Title"]</h4>
    }
    @RenderBody()
</div>

<div class="row justify-content-center mt-5">
    <div class="col">
        <partial name="_BTCPaySupporters"/>
    </div>
</div>

BTCPayServer/Views/Shared/_LayoutWizard.cshtml
@{
    Layout = "_LayoutSimple";
}

@section PageHeadContent {
    <link href="~/main/wizard.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("PageHeadContent", false)
}

@section PageFootContent {
    @await RenderSectionAsync("PageFootContent", false)
}

<nav id="wizard-navbar">
    @await RenderSectionAsync("Navbar", false)
</nav>

<div class="row justify-content-md-center mt-5 pt-sm-3 pt-md-0">
    <main class="col-md-10 col-lg-8 col-xl-7">
        <partial name="_StatusMessage" />
        @RenderBody()
    </main>
</div>

BTCPayServer/Views/Shared/_NavLayout.cshtml
@using NBitcoin
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.ShowMenu = ViewBag.ShowMenu ?? true;
    if (!ViewData.ContainsKey("NavPartialName"))
    {
        ViewData["NavPartialName"] = "_Nav";
    }
}

@section PageHeadContent {
    @await RenderSectionAsync("PageHeadContent", false)
}

@section PageFootContent {
    @await RenderSectionAsync("PageFootContent", false)
}

@if (ViewBag.ShowMenu)
{
    <partial name="@ViewData["NavPartialName"].ToString()" />
    <script>
        (function () {
            const activeEl = document.querySelector('#SectionNav .nav .active')
            if (activeEl) activeEl.scrollIntoView({ block: 'end', inline: 'center' })
        })()
    </script>
}

<partial name="_StatusMessage" />

@RenderBody()

BTCPayServer/Views/Shared/_StatusMessage.cshtml
@using BTCPayServer.Abstractions.Extensions
@{
    var parsedModel = TempData.GetStatusMessageModel();
}

@if (parsedModel != null)
{
    <div class="alert alert-@parsedModel.SeverityCSS @(parsedModel.AllowDismiss? "alert-dismissible":"" ) @(ViewData["Margin"] ?? "mb-4") text-break" role="alert">
        @if (parsedModel.AllowDismiss)
        {
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <vc:icon symbol="close" />
            </button>
        }
        @if (!string.IsNullOrEmpty(parsedModel.Message))
        {
            <span style="white-space: pre-wrap;">@parsedModel.Message</span>
        }
        @if (!string.IsNullOrEmpty(parsedModel.Html))
        {
            @Safe.Raw(parsedModel.Html)
        }
    </div>
}